import { Request, Response } from 'express';
import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcrypt';
import { generateToken } from '../middlewares/auth.middleware';
import config from '../config';
import { auditLog } from '../utils/audit.util';

const prisma = new PrismaClient();

// 生成人员编码
function generateUserCode(tenantId: string): string {
  // 使用租户ID的前4位 + 时间戳 + 随机数
  const prefix = tenantId.substring(0, 4);
  const timestamp = Date.now().toString().slice(-6);
  const random = Math.floor(Math.random() * 1000).toString().padStart(3, '0');
  return `USR${prefix}${timestamp}${random}`;
}

// 中文转拼音工具函数
function convertToPinyin(chinese: string): string {
  // 简单的汉字到拼音转换（使用 Unicode 编码范围）
  const pinyinMap: Record<string, string> = {
    '阿': 'a',
    '啊': 'a',
    '埃': 'ai',
    '挨': 'ai',
    '哎': 'ai',
    '唉': 'ai',
    '哀': 'ai',
    '皑': 'ai',
    '癌': 'ai',
    '矮': 'ai',
    '爱': 'ai',
    '碍': 'ai',
    '安': 'an',
    '按': 'an',
    '暗': 'an',
    '岸': 'an',
    '昂': 'ang',
    '凹': 'ao',
    '敖': 'ao',
    '奥': 'ao',
    '芭': 'ba',
    '八': 'ba',
    '疤': 'ba',
    '巴': 'ba',
    '拔': 'ba',
    '跋': 'ba',
    '靶': 'ba',
    '把': 'ba',
    '坝': 'ba',
    '霸': 'ba',
    '爸': 'ba',
    '白': 'bai',
    '柏': 'bai',
    '百': 'bai',
    '摆': 'bai',
    '佰': 'bai',
    '败': 'bai',
    '拜': 'bai',
    '稗': 'bai',
    '班': 'ban',
    '搬': 'ban',
    '扳': 'ban',
    '般': 'ban',
    '颁': 'ban',
    '板': 'ban',
    '版': 'ban',
    '扮': 'ban',
    '拌': 'ban',
    '瓣': 'ban',
    '办': 'ban',
    '半': 'ban',
    '伴': 'ban',
    '辩': 'bian',
    '边': 'bian',
    '编': 'bian',
    '贬': 'bian',
    '便': 'bian',
    '变': 'bian',
    '卞': 'bian',
    '辨': 'bian',
    '遍': 'bian',
    '标': 'biao',
    '彪': 'biao',
    '膘': 'biao',
    '表': 'biao',
    '鳖': 'bie',
    '憋': 'bie',
    '别': 'bie',
    '瘪': 'bie',
    '彬': 'bin',
    '斌': 'bin',
    '滨': 'bin',
    '濒': 'bin',
    '宾': 'bin',
    '兵': 'bing',
    '冰': 'bing',
    '丙': 'bing',
    '秉': 'bing',
    '柄': 'bing',
    '炳': 'bing',
    '饼': 'bing',
    '禀': 'bing',
    '病': 'bing',
    '并': 'bing',
    '博': 'bo',
    '勃': 'bo',
    '搏': 'bo',
    '铂': 'bo',
    '箔': 'bo',
    '伯': 'bo',
    '帛': 'bo',
    '舶': 'bo',
    '渤': 'bo',
    '卜': 'bu',
    '补': 'bu',
    '不': 'bu',
    '布': 'bu',
    '步': 'bu',
    '部': 'bu',
    '怖': 'bu',
    '擦': 'ca',
    '猜': 'cai',
    '裁': 'cai',
    '材': 'cai',
    '才': 'cai',
    '财': 'cai',
    '踩': 'cai',
    '采': 'cai',
    '彩': 'cai',
    '菜': 'cai',
    '蔡': 'cai',
    '餐': 'can',
    '残': 'can',
    '惭': 'can',
    '惨': 'can',
    '灿': 'can',
    '苍': 'cang',
    '舱': 'cang',
    '仓': 'cang',
    '沧': 'cang',
    '操': 'cao',
    '糙': 'cao',
    '曹': 'cao',
    '草': 'cao',
    '厕': 'ce',
    '策': 'ce',
    '侧': 'ce',
    '册': 'ce',
    '测': 'ce',
    '层': 'ceng',
    '曾': 'ceng',
    '插': 'cha',
    '查': 'cha',
    '茶': 'cha',
    '碴': 'cha',
    '搽': 'cha',
    '察': 'cha',
    '岔': 'cha',
    '差': 'cha',
    '拆': 'chai',
    '柴': 'chai',
    '豺': 'chai',
    '搀': 'chan',
    '蝉': 'chan',
    '馋': 'chan',
    '谗': 'chan',
    '缠': 'chan',
    '铲': 'chan',
    '产': 'chan',
    '阐': 'chan',
    '颤': 'chan',
    '昌': 'chang',
    '场': 'chang',
    '常': 'chang',
    '长': 'chang',
    '偿': 'chang',
    '肠': 'chang',
    '厂': 'chang',
    '敞': 'chang',
    '唱': 'chang',
    '倡': 'chang',
    '超': 'chao',
    '抄': 'chao',
    '钞': 'chao',
    '朝': 'chao',
    '嘲': 'chao',
    '潮': 'chao',
    '巢': 'chao',
    '吵': 'chao',
    '炒': 'chao',
    '车': 'che',
    '扯': 'che',
    '撤': 'che',
    '掣': 'che',
    '彻': 'che',
    '澈': 'che',
    '臣': 'chen',
    '辰': 'chen',
    '尘': 'chen',
    '晨': 'chen',
    '忱': 'chen',
    '沉': 'chen',
    '陈': 'chen',
    '趁': 'chen',
    '衬': 'chen',
    '撑': 'cheng',
    '称': 'cheng',
    '城': 'cheng',
    '橙': 'cheng',
    '成': 'cheng',
    '呈': 'cheng',
    '程': 'cheng',
    '惩': 'cheng',
    '诚': 'cheng',
    '承': 'cheng',
    '逞': 'cheng',
    '吃': 'chi',
    '痴': 'chi',
    '持': 'chi',
    '匙': 'chi',
    '池': 'chi',
    '迟': 'chi',
    '弛': 'chi',
    '耻': 'chi',
    '齿': 'chi',
    '斥': 'chi',
    '赤': 'chi',
    '翅': 'chi',
    '冲': 'chong',
    '充': 'chong',
    '崇': 'chong',
    '抽': 'chou',
    '仇': 'chou',
    '绸': 'chou',
    '瞅': 'chou',
    '丑': 'chou',
    '臭': 'chou',
    '出': 'chu',
    '初': 'chu',
    '厨': 'chu',
    '除': 'chu',
    '锄': 'chu',
    '雏': 'chu',
    '滁': 'chu',
    '储': 'chu',
    '楚': 'chu',
    '础': 'chu',
    '触': 'chu',
    '揣': 'chuai',
    '川': 'chuan',
    '穿': 'chuan',
    '椽': 'chuan',
    '传': 'chuan',
    '船': 'chuan',
    '喘': 'chuan',
    '串': 'chuan',
    '疮': 'chuang',
    '窗': 'chuang',
    '床': 'chuang',
    '创': 'chuang',
    '吹': 'chui',
    '炊': 'chui',
    '垂': 'chui',
    '捶': 'chui',
    '锤': 'chui',
    '春': 'chun',
    '纯': 'chun',
    '唇': 'chun',
    '淳': 'chun',
    '蠢': 'chun',
    '戳': 'chuo',
    '绰': 'chuo',
    '词': 'ci',
    '茨': 'ci',
    '磁': 'ci',
    '雌': 'ci',
    '辞': 'ci',
    '慈': 'ci',
    '瓷': 'ci',
    '此': 'ci',
    '次': 'ci',
    '刺': 'ci',
    '从': 'cong',
    '丛': 'cong',
    '匆': 'cong',
    '葱': 'cong',
    '聪': 'cong',
    '囱': 'cong',
    '凑': 'cou',
    '粗': 'cu',
    '簇': 'cu',
    '促': 'cu',
    '猝': 'cu',
    '醋': 'cu',
    '篡': 'cuan',
    '窜': 'cuan',
    '摧': 'cui',
    '崔': 'cui',
    '催': 'cui',
    '脆': 'cui',
    '瘁': 'cui',
    '粹': 'cui',
    '翠': 'cui',
    '村': 'cun',
    '存': 'cun',
    '寸': 'cun',
    '措': 'cuo',
    '错': 'cuo',
    '挫': 'cuo',
    '搭': 'da',
    '达': 'da',
    '答': 'da',
    '瘩': 'da',
    '打': 'da',
    '大': 'da',
    '呆': 'dai',
    '歹': 'dai',
    '傤': 'dai',
    '带': 'dai',
    '代': 'dai',
    '贷': 'dai',
    '袋': 'dai',
    '待': 'dai',
    '怠': 'dai',
    '逮': 'dai',
    '戴': 'dai',
    '单': 'dan',
    '耽': 'dan',
    '担': 'dan',
    '丹': 'dan',
    '胆': 'dan',
    '旦': 'dan',
    '氮': 'dan',
    '但': 'dan',
    '惮': 'dan',
    '淡': 'dan',
    '弹': 'dan',
    '蛋': 'dan',
    '当': 'dang',
    '挡': 'dang',
    '党': 'dang',
    '刀': 'dao',
    '导': 'dao',
    '倒': 'dao',
    '岛': 'dao',
    '祷': 'dao',
    '捣': 'dao',
    '蹈': 'dao',
    '到': 'dao',
    '悼': 'dao',
    '盗': 'dao',
    '道': 'dao',
    '稻': 'dao',
    '得': 'de',
    '德': 'de',
    '的': 'de',
    '灯': 'deng',
    '登': 'deng',
    '等': 'deng',
    '瞪': 'deng',
    '凳': 'deng',
    '低': 'di',
    '堤': 'di',
    '滴': 'di',
    '迪': 'di',
    '敌': 'di',
    '笛': 'di',
    '狄': 'di',
    '涤': 'di',
    '嫡': 'di',
    '底': 'di',
    '抵': 'di',
    '地': 'di',
    '蒂': 'di',
    '第': 'di',
    '弟': 'di',
    '帝': 'di',
    '缔': 'di',
    '递': 'di',
    '点': 'dian',
    '典': 'dian',
    '电': 'dian',
    '垫': 'dian',
    '店': 'dian',
    '惦': 'dian',
    '奠': 'dian',
    '淀': 'dian',
    '靛': 'dian',
    '雕': 'diao',
    '吊': 'diao',
    '钓': 'diao',
    '调': 'diao',
    '跌': 'die',
    '爹': 'die',
    '碟': 'die',
    '蝶': 'die',
    '迭': 'die',
    '谍': 'die',
    '丁': 'ding',
    '盯': 'ding',
    '叮': 'ding',
    '顶': 'ding',
    '定': 'ding',
    '订': 'ding',
    '丢': 'diu',
    '东': 'dong',
    '冬': 'dong',
    '董': 'dong',
    '懂': 'dong',
    '动': 'dong',
    '栋': 'dong',
    '冻': 'dong',
    '洞': 'dong',
    '斗': 'dou',
    '抖': 'dou',
    '陡': 'dou',
    '豆': 'dou',
    '逗': 'dou',
    '都': 'du',
    '督': 'du',
    '毒': 'du',
    '犊': 'du',
    '独': 'du',
    '堵': 'du',
    '赌': 'du',
    '杜': 'du',
    '镀': 'du',
    '度': 'du',
    '渡': 'du',
    '妒': 'du',
    '端': 'duan',
    '短': 'duan',
    '段': 'duan',
    '断': 'duan',
    '缎': 'duan',
    '锻': 'duan',
    '堆': 'dui',
    '兑': 'dui',
    '队': 'dui',
    '对': 'dui',
    '吨': 'dun',
    '蹲': 'dun',
    '敦': 'dun',
    '顿': 'dun',
    '囤': 'dun',
    '钝': 'dun',
    '盾': 'dun',
    '遁': 'dun',
    '多': 'duo',
    '夺': 'duo',
    '朵': 'duo',
    '躲': 'duo',
    '踱': 'duo',
    '剁': 'duo',
    '惰': 'duo',
    '舵': 'duo',
    '堕': 'duo',
    '蛾': 'e',
    '峨': 'e',
    '鹅': 'e',
    '额': 'e',
    '俄': 'e',
    '恶': 'e',
    '饿': 'e',
    '遏': 'e',
    '鄂': 'e',
    '恩': 'en',
    '儿': 'er',
    '而': 'er',
    '尔': 'er',
    '耳': 'er',
    '饵': 'er',
    '洱': 'er',
    '二': 'er',
    '贰': 'er',
    '发': 'fa',
    '罚': 'fa',
    '筏': 'fa',
    '伐': 'fa',
    '乏': 'fa',
    '阀': 'fa',
    '法': 'fa',
    '藩': 'fan',
    '帆': 'fan',
    '翻': 'fan',
    '樊': 'fan',
    '矾': 'fan',
    '钒': 'fan',
    '繁': 'fan',
    '凡': 'fan',
    '烦': 'fan',
    '反': 'fan',
    '返': 'fan',
    '范': 'fan',
    '贩': 'fan',
    '犯': 'fan',
    '饭': 'fan',
    '泛': 'fan',
    '方': 'fang',
    '坊': 'fang',
    '芳': 'fang',
    '防': 'fang',
    '妨': 'fang',
    '房': 'fang',
    '仿': 'fang',
    '纺': 'fang',
    '飞': 'fei',
    '非': 'fei',
    '啡': 'fei',
    '肥': 'fei',
    '匪': 'fei',
    '诽': 'fei',
    '吠': 'fei',
    '肺': 'fei',
    '废': 'fei',
    '沸': 'fei',
    '费': 'fei',
    '芬': 'fen',
    '酚': 'fen',
    '分': 'fen',
    '纷': 'fen',
    '坟': 'fen',
    '焚': 'fen',
    '汾': 'fen',
    '粉': 'fen',
    '份': 'fen',
    '奋': 'fen',
    '忿': 'fen',
    '愤': 'fen',
    '粪': 'fen',
    '封': 'feng',
    '疯': 'feng',
    '峰': 'feng',
    '丰': 'feng',
    '锋': 'feng',
    '风': 'feng',
    '枫': 'feng',
    '凤': 'feng',
    '奉': 'feng',
    '佛': 'fo',
    '否': 'fou',
    '夫': 'fu',
    '敷': 'fu',
    '肤': 'fu',
    '孵': 'fu',
    '扶': 'fu',
    '拂': 'fu',
    '辐': 'fu',
    '幅': 'fu',
    '氟': 'fu',
    '符': 'fu',
    '伏': 'fu',
    '俘': 'fu',
    '服': 'fu',
    '浮': 'fu',
    '涪': 'fu',
    '福': 'fu',
    '弗': 'fu',
    '甫': 'fu',
    '辅': 'fu',
    '俯': 'fu',
    '釜': 'fu',
    '脯': 'fu',
    '腑': 'fu',
    '府': 'fu',
    '腐': 'fu',
    '赴': 'fu',
    '副': 'fu',
    '覆': 'fu',
    '赋': 'fu',
    '复': 'fu',
    '傅': 'fu',
    '付': 'fu',
    '阜': 'fu',
    '父': 'fu',
    '腹': 'fu',
    '负': 'fu',
    '富': 'fu',
    '附': 'fu',
    '妇': 'fu',
    '缚': 'fu',
    '噶': 'ga',
    '嘎': 'ga',
    '该': 'gai',
    '改': 'gai',
    '钙': 'gai',
    '盖': 'gai',
    '概': 'gai',
    '干': 'gan',
    '杆': 'gan',
    '柑': 'gan',
    '竿': 'gan',
    '感': 'gan',
    '敢': 'gan',
    '赣': 'gan',
    '刚': 'gang',
    '杠': 'gang',
    '纲': 'gang',
    '岗': 'gang',
    '港': 'gang',
    '高': 'gao',
    '膏': 'gao',
    '羔': 'gao',
    '糕': 'gao',
    '搞': 'gao',
    '镐': 'gao',
    '告': 'gao',
    '哥': 'ge',
    '歌': 'ge',
    '搁': 'ge',
    '鸽': 'ge',
    '割': 'ge',
    '革': 'ge',
    '葛': 'ge',
    '格': 'ge',
    '蛤': 'ge',
    '阁': 'ge',
    '隔': 'ge',
    '铬': 'ge',
    '个': 'ge',
    '各': 'ge',
    '给': 'gei',
    '根': 'gen',
    '跟': 'gen',
    '耕': 'geng',
    '更': 'geng',
    '庚': 'geng',
    '羹': 'geng',
    '工': 'gong',
    '攻': 'gong',
    '功': 'gong',
    '恭': 'gong',
    '龚': 'gong',
    '供给': 'gong',
    '供': 'gong',
    '共': 'gong',
    '勾': 'gou',
    '沟': 'gou',
    '狗': 'gou',
    '苟': 'gou',
    '构': 'gou',
    '购': 'gou',
    '垢': 'gou',
    '够': 'gou',
    '辜': 'gu',
    '咕': 'gu',
    '姑': 'gu',
    '估': 'gu',
    '孤': 'gu',
    '古': 'gu',
    '蛊': 'gu',
    '骨': 'gu',
    '谷': 'gu',
    '股': 'gu',
    '故': 'gu',
    '顾': 'gu',
    '雇': 'gu',
    '固': 'gu',
    '挂': 'gua',
    '乖': 'guai',
    '拐': 'guai',
    '怪': 'guai',
    '关': 'guan',
    '官': 'guan',
    '冠': 'guan',
    '棺': 'guan',
    '管': 'guan',
    '馆': 'guan',
    '罐': 'guan',
    '惯': 'guan',
    '灌': 'guan',
    '光': 'guang',
    '广': 'guang',
    '逛': 'guang',
    '归': 'gui',
    '瑰': 'gui',
    '龟': 'gui',
    '规': 'gui',
    '硅': 'gui',
    '闺': 'gui',
    '轨': 'gui',
    '鬼': 'gui',
    '诡': 'gui',
    '桂': 'gui',
    '柜': 'gui',
    '跪': 'gui',
    '贵': 'gui',
    '滚': 'gun',
    '棍': 'gun',
    '国': 'guo',
    '果': 'guo',
    '裹': 'guo',
    '过': 'guo',
    '哈': 'ha',
    '骸': 'hai',
    '孩': 'hai',
    '海': 'hai',
    '氦': 'hai',
    '亥': 'hai',
    '害': 'hai',
    '骇': 'hai',
    '韩': 'han',
    '含': 'han',
    '涵': 'han',
    '寒': 'han',
    '函': 'han',
    '喊': 'han',
    '罕': 'han',
    '翰': 'han',
    '旱': 'han',
    '憾': 'han',
    '悍': 'han',
    '焊': 'han',
    '汉': 'han',
    '撼': 'han',
    '航': 'hang',
    '杭': 'hang',
    '豪': 'hao',
    '毫': 'hao',
    '郝': 'hao',
    '好': 'hao',
    '耗': 'hao',
    '浩': 'hao',
    '号': 'hao',
    '呵': 'he',
    '喝': 'he',
    '荷': 'he',
    '核': 'he',
    '禾': 'he',
    '和': 'he',
    '何': 'he',
    '合': 'he',
    '盒': 'he',
    '阂': 'he',
    '河': 'he',
    '涸': 'he',
    '赫': 'he',
    '褐': 'he',
    '鹤': 'he',
    '贺': 'he',
    '黑': 'hei',
    '嘿': 'hei',
    '痕': 'hen',
    '很': 'hen',
    '狠': 'hen',
    '恨': 'hen',
    '哼': 'heng',
    '恒': 'heng',
    '横': 'heng',
    '衡': 'heng',
    '轰': 'hong',
    '哄': 'hong',
    '烘': 'hong',
    '虹': 'hong',
    '鸿': 'hong',
    '洪': 'hong',
    '宏': 'hong',
    '弘': 'hong',
    '红': 'hong',
    '喉': 'hou',
    '侯': 'hou',
    '猴': 'hou',
    '吼': 'hou',
    '厚': 'hou',
    '候': 'hou',
    '后': 'hou',
    '呼': 'hu',
    '乎': 'hu',
    '忽': 'hu',
    '瑚': 'hu',
    '壶': 'hu',
    '胡': 'hu',
    '蝴': 'hu',
    '湖': 'hu',
    '弧': 'hu',
    '虎': 'hu',
    '护': 'hu',
    '互': 'hu',
    '沪': 'hu',
    '户': 'hu',
    '花': 'hua',
    '哗': 'hua',
    '华': 'hua',
    '滑': 'hua',
    '画': 'hua',
    '划': 'hua',
    '化': 'hua',
    '话': 'hua',
    '槐': 'huai',
    '坏': 'huai',
    '欢': 'huan',
    '环': 'huan',
    '桓': 'huan',
    '缓': 'huan',
    '换': 'huan',
    '唤': 'huan',
    '焕': 'huan',
    '幻': 'huan',
    '宜': 'huan',
    '荒': 'huang',
    '慌': 'huang',
    '黄': 'huang',
    '磺': 'huang',
    '蝗': 'huang',
    '簧': 'huang',
    '皇': 'huang',
    '凰': 'huang',
    '惶': 'huang',
    '晃': 'huang',
    '谎': 'huang',
    '幌': 'huang',
    '灰': 'hui',
    '挥': 'hui',
    '辉': 'hui',
    '徽': 'hui',
    '恢': 'hui',
    '蛔': 'hui',
    '回': 'hui',
    '毁': 'hui',
    '悔': 'hui',
    '慧': 'hui',
    '惠': 'hui',
    '晦': 'hui',
    '秽': 'hui',
    '会': 'hui',
    '汇': 'hui',
    '绘': 'hui',
    '诲': 'hui',
    '昏': 'hun',
    '荤': 'hun',
    '婚': 'hun',
    '浑': 'hun',
    '魂': 'hun',
    '混': 'hun',
    '豁': 'huo',
    '活': 'huo',
    '火': 'huo',
    '获': 'huo',
    '或': 'huo',
    '惑': 'huo',
    '霍': 'huo',
    '货': 'huo',
    '祸': 'huo',
    '击': 'ji',
    '基': 'ji',
    '机': 'ji',
    '讥': 'ji',
    '畸': 'ji',
    '积': 'ji',
    '激': 'ji',
    '及': 'ji',
    '汲': 'ji',
    '嫉': 'ji',
    '级': 'ji',
    '挤': 'ji',
    '几': 'ji',
    '脊': 'ji',
    '已': 'ji',
    '蓟': 'ji',
    '技': 'ji',
    '冀': 'ji',
    '季': 'ji',
    '伎': 'ji',
    '祭': 'ji',
    '剂': 'ji',
    '悸': 'ji',
    '济': 'ji',
    '寄': 'ji',
    '寂': 'ji',
    '计': 'ji',
    '记': 'ji',
    '既': 'ji',
    '忌': 'ji',
    '际': 'ji',
    '妓': 'ji',
    '继': 'ji',
    '纪': 'ji',
    '嘉': 'jia',
    '枷': 'jia',
    '夹': 'jia',
    '佳': 'jia',
    '家': 'jia',
    '加': 'jia',
    '荚': 'jia',
    '颊': 'jia',
    '贾': 'jia',
    '甲': 'jia',
    '钾': 'jia',
    '假': 'jia',
    '稼': 'jia',
    '价': 'jia',
    '架': 'jia',
    '驾': 'jia',
    '嫁': 'jia',
    '监': 'jian',
    '尖': 'jian',
    '坚': 'jian',
    '间': 'jian',
    '肩': 'jian',
    '艰': 'jian',
    '兼': 'jian',
    '奸': 'jian',
    '茧': 'jian',
    '柬': 'jian',
    '检': 'jian',
    '碱': 'jian',
    '简': 'jian',
    '俭': 'jian',
    '剪': 'jian',
    '减': 'jian',
    '荐': 'jian',
    '践': 'jian',
    '贱': 'jian',
    '见': 'jian',
    '键': 'jian',
    '舰': 'jian',
    '剑': 'jian',
    '饯': 'jian',
    '渐': 'jian',
    '溅': 'jian',
    '涧': 'jian',
    '将': 'jiang',
    '浆': 'jiang',
    '蒋': 'jiang',
    '江': 'jiang',
    '僵': 'jiang',
    '姜': 'jiang',
    '讲': 'jiang',
    '奖': 'jiang',
    '匠': 'jiang',
    '酱': 'jiang',
    '降': 'jiang',
    '交': 'jiao',
    '郊': 'jiao',
    '浇': 'jiao',
    '骄': 'jiao',
    '娇': 'jiao',
    '焦': 'jiao',
    '胶': 'jiao',
    '角': 'jiao',
    '狡': 'jiao',
    '饺': 'jiao',
    '绞': 'jiao',
    '脚': 'jiao',
    '缴': 'jiao',
    '叫': 'jiao',
    '轿': 'jiao',
    '较': 'jiao',
    '窖': 'jiao',
    '校': 'jiao',
    '教': 'jiao',
    '酵': 'jiao',
    '节': 'jie',
    '劫': 'jie',
    '杰': 'jie',
    '洁': 'jie',
    '结': 'jie',
    '捷': 'jie',
    '睫': 'jie',
    '截': 'jie',
    '竭': 'jie',
    '皆': 'jie',
    '戒': 'jie',
    '届': 'jie',
    '借': 'jie',
    '介': 'jie',
    '疥': 'jie',
    '芥': 'jie',
    '今': 'jin',
    '金': 'jin',
    '津': 'jin',
    '筋': 'jin',
    '襟': 'jin',
    '仅': 'jin',
    '紧': 'jin',
    '锦': 'jin',
    '尽': 'jin',
    '谨': 'jin',
    '进': 'jin',
    '靳': 'jin',
    '晋': 'jin',
    '禁': 'jin',
    '近': 'jin',
    '烬': 'jin',
    '浸': 'jin',
    '劲': 'jing',
    '荆': 'jing',
    '惊': 'jing',
    '晶': 'jing',
    '睛': 'jing',
    '精': 'jing',
    '经': 'jing',
    '井': 'jing',
    '警': 'jing',
    '景': 'jing',
    '颈': 'jing',
    '静': 'jing',
    '境': 'jing',
    '敬': 'jing',
    '镜': 'jing',
    '竞': 'jing',
    '净': 'jing',
    '径': 'jing',
    '痉': 'jing',
    '靖': 'jing',
    '竟': 'jing',
    '窘': 'jiong',
    '纠': 'jiu',
    '玖': 'jiu',
    '久': 'jiu',
    '灸': 'jiu',
    '九': 'jiu',
    '酒': 'jiu',
    '旧': 'jiu',
    '救': 'jiu',
    '就': 'jiu',
    '舅': 'jiu',
    '咎': 'jiu',
    '疚': 'jiu',
    '鞠': 'ju',
    '狙': 'ju',
    '拘': 'ju',
    '疽': 'ju',
    '居': 'ju',
    '驹': 'ju',
    '菊': 'ju',
    '局': 'ju',
    '咀': 'ju',
    '矩': 'ju',
    '举': 'ju',
    '聚': 'ju',
    '拒': 'ju',
    '巨': 'ju',
    '具': 'ju',
    '炬': 'ju',
    '踞': 'ju',
    '剧': 'ju',
    '俱': 'ju',
    '惧': 'ju',
    '句': 'ju',
    '据': 'ju',
    '距': 'ju',
    '锯': 'ju',
    '卷': 'juan',
    '眷': 'juan',
    '绢': 'juan',
    '撅': 'jue',
    '抉': 'jue',
    '掘': 'jue',
    '倔': 'jue',
    '爵': 'jue',
    '觉': 'jue',
    '决': 'jue',
    '诀': 'jue',
    '绝': 'jue',
    '均': 'jun',
    '菌': 'jun',
    '钧': 'jun',
    '军': 'jun',
    '君': 'jun',
    '峻': 'jun',
    '俊': 'jun',
    '郡': 'jun',
    '骏': 'jun',
    '喀': 'ka',
    '卡': 'ka',
    '开': 'kai',
    '揩': 'kai',
    '凯': 'kai',
    '刊': 'kan',
    '勘': 'kan',
    '坎': 'kan',
    '看': 'kan',
    '康': 'kang',
    '慷': 'kang',
    '扛': 'kang',
    '抗': 'kang',
    '亢': 'kang',
    '炕': 'kang',
    '考': 'kao',
    '拷': 'kao',
    '靠': 'kao',
    '颗': 'ke',
    '科': 'ke',
    '壳': 'ke',
    '咳': 'ke',
    '可': 'ke',
    '渴': 'ke',
    '克': 'ke',
    '刻': 'ke',
    '客': 'ke',
    '课': 'ke',
    '肯': 'ken',
    '啃': 'ken',
    '恳': 'ken',
    '坑': 'keng',
    '铿': 'keng',
    '空': 'kong',
    '恐': 'kong',
    '孔': 'kong',
    '控': 'kong',
    '抠': 'kou',
    '口': 'kou',
    '扣': 'kou',
    '寇': 'kou',
    '苦': 'ku',
    '库': 'ku',
    '裤': 'ku',
    '酷': 'ku',
    '夸': 'kua',
    '垮': 'kua',
    '挎': 'kua',
    '跨': 'kua',
    '胯': 'kua',
    '块': 'kuai',
    '快': 'kuai',
    '筷': 'kuai',
    '宽': 'kuan',
    '款': 'kuan',
    '狂': 'kuang',
    '旷': 'kuang',
    '况': 'kuang',
    '矿': 'kuang',
    '眶': 'kuang',
    '框': 'kuang',
    '亏': 'kui',
    '盔': 'kui',
    '窥': 'kui',
    '葵': 'kui',
    '傀': 'kui',
    '愧': 'kui',
    '溃': 'kui',
    '坤': 'kun',
    '昆': 'kun',
    '捆': 'kun',
    '困': 'kun',
    '括': 'kuo',
    '扩': 'kuo',
    '阔': 'kuo',
    '廓': 'kuo',
    '拉': 'la',
    '啦': 'la',
    '蜡': 'la',
    '腊': 'la',
    '辣': 'la',
    '莱': 'lai',
    '来': 'lai',
    '赖': 'lai',
    '蓝': 'lan',
    '栏': 'lan',
    '拦': 'lan',
    '篮': 'lan',
    '阑': 'lan',
    '兰': 'lan',
    '澜': 'lan',
    '谰': 'lan',
    '揽': 'lan',
    '览': 'lan',
    '懒': 'lan',
    '缆': 'lan',
    '烂': 'lan',
    '滥': 'lan',
    '郎': 'lang',
    '狼': 'lang',
    '廊': 'lang',
    '朗': 'lang',
    '浪': 'lang',
    '捞': 'lao',
    '劳': 'lao',
    '牢': 'lao',
    '老': 'lao',
    '佬': 'lao',
    '姥': 'lao',
    '酪': 'lao',
    '烙': 'lao',
    '涝': 'lao',
    '乐': 'le',
    '勒': 'le',
    '雷': 'lei',
    '垒': 'lei',
    '磊': 'lei',
    '蕾': 'lei',
    '累': 'lei',
    '泪': 'lei',
    '棱': 'leng',
    '冷': 'leng',
    '愣': 'leng',
    '梨': 'li',
    '黎': 'li',
    '犁': 'li',
    '狸': 'li',
    '篱': 'li',
    '璃': 'li',
    '礼': 'li',
    '李': 'li',
    '里': 'li',
    '理': 'li',
    '鲤': 'li',
    '力': 'li',
    '历': 'li',
    '厉': 'li',
    '立': 'li',
    '粒': 'li',
    '沥': 'li',
    '隶': 'li',
    '联': 'lian',
    '莲': 'lian',
    '连': 'lian',
    '镰': 'lian',
    '廉': 'lian',
    '怜': 'lian',
    '涟': 'lian',
    '帘': 'lian',
    '敛': 'lian',
    '脸': 'lian',
    '链': 'lian',
    '恋': 'lian',
    '炼': 'lian',
    '练': 'lian',
    '粮': 'liang',
    '凉': 'liang',
    '梁': 'liang',
    '良': 'liang',
    '两': 'liang',
    '辆': 'liang',
    '量': 'liang',
    '晾': 'liang',
    '亮': 'liang',
    '谅': 'liang',
    '聊': 'liao',
    '辽': 'liao',
    '疗': 'liao',
    '燎': 'liao',
    '了': 'liao',
    '料': 'liao',
    '撂': 'liao',
    '列': 'lie',
    '烈': 'lie',
    '猎': 'lie',
    '裂': 'lie',
    '劣': 'lie',
    '邻': 'lin',
    '林': 'lin',
    '临': 'lin',
    '淋': 'lin',
    '磷': 'lin',
    '琳': 'lin',
    '凛': 'lin',
    '吝': 'lin',
    '拎': 'lin',
    '玲': 'ling',
    '菱': 'ling',
    '零': 'ling',
    '龄': 'ling',
    '铃': 'ling',
    '灵': 'ling',
    '岭': 'ling',
    '领': 'ling',
    '另': 'ling',
    '令': 'ling',
    '溜': 'liu',
    '流': 'liu',
    '留': 'liu',
    '琉': 'liu',
    '硫': 'liu',
    '馏': 'liu',
    '刘': 'liu',
    '柳': 'liu',
    '六': 'liu',
    '龙': 'long',
    '聋': 'long',
    '咙': 'long',
    '笼': 'long',
    '隆': 'long',
    '垄': 'long',
    '拢': 'long',
    '楼': 'lou',
    '娄': 'lou',
    '搂': 'lou',
    '篓': 'lou',
    '漏': 'lou',
    '陋': 'lou',
    '芦': 'lu',
    '卢': 'lu',
    '颅': 'lu',
    '庐': 'lu',
    '炉': 'lu',
    '掳': 'lu',
    '卤': 'lu',
    '虏': 'lu',
    '鲁': 'lu',
    '麓': 'lu',
    '陆': 'lu',
    '录': 'lu',
    '鹿': 'lu',
    '路': 'lu',
    '露': 'lu',
    '禄': 'lu',
    '旅': 'lv',
    '吕': 'lv',
    '铝': 'lv',
    '履': 'lv',
    '律': 'lv',
    '虑': 'lv',
    '氯': 'lv',
    '滤': 'lv',
    '率': 'lv',
    '绿': 'lv',
    '峦': 'luan',
    '挛': 'luan',
    '滦': 'luan',
    '卵': 'luan',
    '乱': 'luan',
    '掠': 'lve',
    '略': 'lve',
    '抡': 'lun',
    '伦': 'lun',
    '沦': 'lun',
    '轮': 'lun',
    '论': 'lun',
    '罗': 'luo',
    '洛': 'luo',
    '逻': 'luo',
    '锣': 'luo',
    '箩': 'luo',
    '螺': 'luo',
    '落': 'luo',
    '妈': 'ma',
    '麻': 'ma',
    '玛': 'ma',
    '码': 'ma',
    '蚂': 'ma',
    '马': 'ma',
    '骂': 'ma',
    '吗': 'ma',
    '嘛': 'ma',
    '埋': 'mai',
    '买': 'mai',
    '麦': 'mai',
    '卖': 'mai',
    '迈': 'mai',
    '瞒': 'man',
    '馒': 'man',
    '满': 'man',
    '蔓': 'man',
    '慢': 'man',
    '漫': 'man',
    '芒': 'mang',
    '茫': 'mang',
    '盲': 'mang',
    '忙': 'mang',
    '莽': 'mang',
    '猫': 'mao',
    '茅': 'mao',
    '锚': 'mao',
    '毛': 'mao',
    '矛': 'mao',
    '卯': 'mao',
    '冒': 'mao',
    '帽': 'mao',
    '貌': 'mao',
    '贸': 'mao',
    '么': 'me',
    '玫': 'mei',
    '枚': 'mei',
    '梅': 'mei',
    '酶': 'mei',
    '霉': 'mei',
    '没': 'mei',
    '眉': 'mei',
    '媒': 'mei',
    '镁': 'mei',
    '美': 'mei',
    '昧': 'mei',
    '寐': 'mei',
    '妹': 'mei',
    '媚': 'mei',
    '门': 'men',
    '闷': 'men',
    '们': 'men',
    '萌': 'meng',
    '蒙': 'meng',
    '盟': 'meng',
    '锰': 'meng',
    '梦': 'meng',
    '孟': 'meng',
    '眯': 'mi',
    '醚': 'mi',
    '弥': 'mi',
    '迷': 'mi',
    '谜': 'mi',
    '米': 'mi',
    '秘': 'mi',
    '觅': 'mi',
    '泌': 'mi',
    '蜜': 'mi',
    '密': 'mi',
    '幂': 'mi',
    '棉': 'mian',
    '眠': 'mian',
    '绵': 'mian',
    '冕': 'mian',
    '免': 'mian',
    '勉': 'mian',
    '娩': 'mian',
    '面': 'mian',
    '苗': 'miao',
    '描': 'miao',
    '瞄': 'miao',
    '藐': 'miao',
    '秒': 'miao',
    '妙': 'miao',
    '庙': 'miao',
    '灭': 'mie',
    '蔑': 'mie',
    '民': 'min',
    '皿': 'min',
    '敏': 'min',
    '闽': 'min',
    '泯': 'min',
    '抿': 'min',
    '明': 'ming',
    '螟': 'ming',
    '鸣': 'ming',
    '铭': 'ming',
    '名': 'ming',
    '命': 'ming',
    '谬': 'miu',
    '摸': 'mo',
    '摹': 'mo',
    '膜': 'mo',
    '磨': 'mo',
    '蘑': 'mo',
    '魔': 'mo',
    '抹': 'mo',
    '末': 'mo',
    '莫': 'mo',
    '默': 'mo',
    '沫': 'mo',
    '漠': 'mo',
    '陌': 'mo',
    '墨': 'mo',
    '脉': 'mo',
    '牟': 'mu',
    '模': 'mu',
    '母': 'mu',
    '亩': 'mu',
    '牡': 'mu',
    '姆': 'mu',
    '墓': 'mu',
    '幕': 'mu',
    '慕': 'mu',
    '暮': 'mu',
    '穆': 'mu',
    '拿': 'na',
    '哪': 'na',
    '呐': 'na',
    '钠': 'na',
    '那': 'na',
    '娜': 'na',
    '纳': 'na',
    '乃': 'nai',
    '奶': 'nai',
    '耐': 'nai',
    '奈': 'nai',
    '南': 'nan',
    '男': 'nan',
    '难': 'nan',
    '囊': 'nang',
    '挠': 'nao',
    '脑': 'nao',
    '恼': 'nao',
    '闹': 'nao',
    '淖': 'nao',
    '呢': 'ne',
    '嫩': 'nen',
    '能': 'neng',
    '妮': 'ni',
    '霓': 'ni',
    '倪': 'ni',
    '泥': 'ni',
    '尼': 'ni',
    '拟': 'ni',
    '你': 'ni',
    '匿': 'ni',
    '腻': 'ni',
    '逆': 'ni',
    '溺': 'ni',
    '蔫': 'nian',
    '拈': 'nian',
    '年': 'nian',
    '碾': 'nian',
    '撵': 'nian',
    '念': 'nian',
    '捻': 'nian',
    '娘': 'niang',
    '酿': 'niang',
    '鸟': 'niao',
    '尿': 'niao',
    '捏': 'nie',
    '聂': 'nie',
    '孽': 'nie',
    '啮': 'nie',
    '镊': 'nie',
    '镍': 'nie',
    '涅': 'nie',
    '您': 'nin',
    '柠': 'ning',
    '狞': 'ning',
    '凝': 'ning',
    '宁': 'ning',
    '拧': 'ning',
    '泞': 'ning',
    '牛': 'niu',
    '扭': 'niu',
    '钮': 'niu',
    '纽': 'niu',
    '脓': 'nong',
    '浓': 'nong',
    '农': 'nong',
    '弄': 'nong',
    '奴': 'nu',
    '努': 'nu',
    '怒': 'nu',
    '暖': 'nuan',
    '女': 'nv',
    '虐': 'nve',
    '疟': 'nve',
    '挪': 'nuo',
    '懦': 'nuo',
    '糯': 'nuo',
    '诺': 'nuo',
    '哦': 'o',
    '欧': 'ou',
    '鸥': 'ou',
    '呕': 'ou',
    '偶': 'ou',
    '藕': 'ou',
    '沤': 'ou',
    '啪': 'pa',
    '爬': 'pa',
    '帕': 'pa',
    '怕': 'pa',
    '排': 'pai',
    '牌': 'pai',
    '派': 'pai',
    '拍': 'pai',
    '裴': 'pei',
    '沛': 'pei',
    '盆': 'pen',
    '烹': 'peng',
    '彭': 'peng',
    '棚': 'peng',
    '蓬': 'peng',
    '硼': 'peng',
    '膨': 'peng',
    '鹏': 'peng',
    '碰': 'peng',
    '坯': 'pi',
    '砒': 'pi',
    '批': 'pi',
    '披': 'pi',
    '劈': 'pi',
    '皮': 'pi',
    '匹': 'pi',
    '痞': 'pi',
    '癖': 'pi',
    '屁': 'pi',
    '僻': 'pi',
    '壁': 'bi',
    '臂': 'bi',
    '避': 'bi',
    '碧': 'bi',
    '蔽': 'bi',
    '毕': 'bi',
    '毙': 'bi',
    '毖': 'bi',
    '币': 'bi',
    '庇': 'bi',
    '偏': 'pian',
    '篇': 'pian',
    '骗': 'pian',
    '片': 'pian',
    '飘': 'piao',
    '漂': 'piao',
    '瓢': 'piao',
    '票': 'piao',
    '撇': 'pie',
    '瞥': 'pie',
    '拼': 'pin',
    '频': 'pin',
    '贫': 'pin',
    '品': 'pin',
    '聘': 'pin',
    '乒': 'ping',
    '坪': 'ping',
    '萍': 'ping',
    '平': 'ping',
    '凭': 'ping',
    '屏': 'ping',
    '评': 'ping',
    '颇': 'po',
    '坡': 'po',
    '泼': 'po',
    '婆': 'po',
    '迫': 'po',
    '破': 'po',
    '粕': 'po',
    '魄': 'po',
    '剖': 'pou',
    '扑': 'pu',
    '铺': 'pu',
    '仆': 'pu',
    '莆': 'pu',
    '葡': 'pu',
    '菩': 'pu',
    '蒲': 'pu',
    '埔': 'pu',
    '朴': 'pu',
    '圃': 'pu',
    '普': 'pu',
    '谱': 'pu',
    '浦': 'pu',
    '暴': 'pu',
    '七': 'qi',
    '期': 'qi',
    '欺': 'qi',
    '戚': 'qi',
    '妻': 'qi',
    '凄': 'qi',
    '染': 'qi',
    '其': 'qi',
    '棋': 'qi',
    '奇': 'qi',
    '歧': 'qi',
    '崎': 'qi',
    '脐': 'qi',
    '旗': 'qi',
    '祈': 'qi',
    '祁': 'qi',
    '骑': 'qi',
    '起': 'qi',
    '岂': 'qi',
    '乞': 'qi',
    '企': 'qi',
    '启': 'qi',
    '契': 'qi',
    '砌': 'qi',
    '泣': 'qi',
    '气': 'qi',
    '器': 'qi',
    '汽': 'qi',
    '讫': 'qi',
    '弃': 'qi',
    '掐': 'qia',
    '恰': 'qia',
    '洽': 'qia',
    '牵': 'qian',
    '扦': 'qian',
    '钎': 'qian',
    '铅': 'qian',
    '千': 'qian',
    '迁': 'qian',
    '签': 'qian',
    '仟': 'qian',
    '谦': 'qian',
    '乾': 'qian',
    '黔': 'qian',
    '前': 'qian',
    '钱': 'qian',
    '钳': 'qian',
    '潜': 'qian',
    '浅': 'qian',
    '遣': 'qian',
    '欠': 'qian',
    '纤': 'qian',
    '堑': 'qian',
    '嵌': 'qian',
    '枪': 'qiang',
    '呛': 'qiang',
    '腔': 'qiang',
    '羌': 'qiang',
    '墙': 'qiang',
    '蔷': 'qiang',
    '强': 'qiang',
    '抢': 'qiang',
    '悄': 'qiao',
    '桥': 'qiao',
    '瞧': 'qiao',
    '乔': 'qiao',
    '侨': 'qiao',
    '巧': 'qiao',
    '鞘': 'qiao',
    '翘': 'qiao',
    '峭': 'qiao',
    '俏': 'qiao',
    '窍': 'qiao',
    '切': 'qie',
    '茄': 'qie',
    '且': 'qie',
    '怯': 'qie',
    '窃': 'qie',
    '侵': 'qin',
    '钦': 'qin',
    '亲': 'qin',
    '琴': 'qin',
    '勤': 'qin',
    '芹': 'qin',
    '擒': 'qin',
    '禽': 'qin',
    '寝': 'qin',
    '秦': 'qin',
    '沁': 'qin',
    '青': 'qing',
    '轻': 'qing',
    '氢': 'qing',
    '倾': 'qing',
    '卿': 'qing',
    '清': 'qing',
    '擎': 'qing',
    '晴': 'qing',
    '氰': 'qing',
    '情': 'qing',
    '请': 'qing',
    '庆': 'qing',
    '琼': 'qiong',
    '穷': 'qiong',
    '秋': 'qiu',
    '丘': 'qiu',
    '邱': 'qiu',
    '球': 'qiu',
    '求': 'qiu',
    '囚': 'qiu',
    '酋': 'qiu',
    '泅': 'qiu',
    '趋': 'qu',
    '区': 'qu',
    '曲': 'qu',
    '驱': 'qu',
    '屈': 'qu',
    '躯': 'qu',
    '渠': 'qu',
    '取': 'qu',
    '娶': 'qu',
    '龋': 'qu',
    '去': 'qu',
    '趣': 'qu',
    '圈': 'quan',
    '颧': 'quan',
    '权': 'quan',
    '全': 'quan',
    '泉': 'quan',
    '拳': 'quan',
    '犬': 'quan',
    '券': 'quan',
    '劝': 'quan',
    '缺': 'que',
    '炔': 'que',
    '却': 'que',
    '鹊': 'que',
    '雀': 'que',
    '确': 'que',
    '阕': 'que',
    '裙': 'qun',
    '群': 'qun',
    '然': 'ran',
    '燃': 'ran',
    '冉': 'ran',
    '瓤': 'rang',
    '壤': 'rang',
    '攘': 'rang',
    '嚷': 'rang',
    '让': 'rang',
    '饶': 'rao',
    '扰': 'rao',
    '绕': 'rao',
    '热': 're',
    '惹': 're',
    '人': 'ren',
    '仁': 'ren',
    '任': 'ren',
    '忍': 'ren',
    '认': 'ren',
    '刃': 'ren',
    '壬': 'ren',
    '纫': 'ren',
    '扔': 'reng',
    '仍': 'reng',
    '日': 'ri',
    '戎': 'rong',
    '茸': 'rong',
    '蓉': 'rong',
    '荣': 'rong',
    '融': 'rong',
    '熔': 'rong',
    '溶': 'rong',
    '绒': 'rong',
    '容': 'rong',
    '冗': 'rong',
    '柔': 'rou',
    '揉': 'rou',
    '肉': 'rou',
    '糅': 'rou',
    '如': 'ru',
    '茹': 'ru',
    '蠕': 'ru',
    '儒': 'ru',
    '濡': 'ru',
    '孺': 'ru',
    '辱': 'ru',
    '汝': 'ru',
    '入': 'ru',
    '褥': 'ru',
    '软': 'ruan',
    '阮': 'ruan',
    '锐': 'rui',
    '瑞': 'rui',
    '芮': 'rui',
    '闰': 'run',
    '润': 'run',
    '若': 'ruo',
    '弱': 'ruo',
    '撒': 'sa',
    '洒': 'sa',
    '萨': 'sa',
    '腮': 'sai',
    '鳃': 'sai',
    '赛': 'sai',
    '三': 'san',
    '叁': 'san',
    '伞': 'san',
    '散': 'san',
    '桑': 'sang',
    '嗓': 'sang',
    '丧': 'sang',
    '扫': 'sao',
    '嫂': 'sao',
    '色': 'se',
    '涩': 'se',
    '瑟': 'se',
    '啬': 'se',
    '森': 'sen',
    '僧': 'seng',
    '沙': 'sha',
    '砂': 'sha',
    '傻': 'sha',
    '纱': 'sha',
    '刹': 'sha',
    '啥': 'sha',
    '筛': 'shai',
    '晒': 'shai',
    '删': 'shan',
    '姗': 'shan',
    '衫': 'shan',
    '栅': 'shan',
    '珊': 'shan',
    '擅': 'shan',
    '膳': 'shan',
    '善': 'shan',
    '扇': 'shan',
    '山': 'shan',
    '陕': 'shan',
    '讪': 'shan',
    '汕': 'shan',
    '商': 'shang',
    '赏': 'shang',
    '晌': 'shang',
    '上': 'shang',
    '尚': 'shang',
    '伤': 'shang',
    '殇': 'shang',
    '裳': 'shang',
    '勺': 'shao',
    '韶': 'shao',
    '少': 'shao',
    '邵': 'shao',
    '绍': 'shao',
    '哨': 'shao',
    '梢': 'shao',
    '捎': 'shao',
    '烧': 'shao',
    '稍': 'shao',
    '艄': 'shao',
    'she': 'she',
    '奢': 'she',
    '赊': 'she',
    '蛇': 'she',
    '舌': 'she',
    '舍': 'she',
    '赦': 'she',
    '摄': 'she',
    '射': 'she',
    '涉': 'she',
    '社': 'she',
    '谁': 'shei',
    '身': 'shen',
    '深': 'shen',
    '甚': 'shen',
    '什': 'shen',
    '呻': 'shen',
    '婶': 'shen',
    '审': 'shen',
    '慎': 'shen',
    '肾': 'shen',
    '渗': 'shen',
    '参': 'shen',
    '生': 'sheng',
    '甥': 'sheng',
    '笙': 'sheng',
    '声': 'sheng',
    '绳': 'sheng',
    '省': 'sheng',
    '盛': 'sheng',
    '剩': 'sheng',
    '胜': 'sheng',
    '圣': 'sheng',
    '失': 'shi',
    '师': 'shi',
    '狮': 'shi',
    '施': 'shi',
    '湿': 'shi',
    '诗': 'shi',
    '尸': 'shi',
    '十': 'shi',
    '拾': 'shi',
    '石': 'shi',
    '时': 'shi',
    '蚀': 'shi',
    '实': 'shi',
    '识': 'shi',
    '史': 'shi',
    '矢': 'shi',
    '使': 'shi',
    '屎': 'shi',
    '始': 'shi',
    '驶': 'shi',
    '士': 'shi',
    '世': 'shi',
    '柿': 'shi',
    '市': 'shi',
    '恃': 'shi',
    '室': 'shi',
    '视': 'shi',
    '试': 'shi',
    '收': 'shou',
    '手': 'shou',
    '守': 'shou',
    '首': 'shou',
    '寿': 'shou',
    '受': 'shou',
    '授': 'shou',
    '售': 'shou',
    '兽': 'shou',
    '瘦': 'shou',
    '疏': 'shu',
    '书': 'shu',
    '输': 'shu',
    '殊': 'shu',
    '抒': 'shu',
    '舒': 'shu',
    '叔': 'shu',
    '枢': 'shu',
    '暑': 'shu',
    '黍': 'shu',
    '署': 'shu',
    '蜀': 'shu',
    '鼠': 'shu',
    '数': 'shu',
    '薯': 'shu',
    '曙': 'shu',
    '术': 'shu',
    '树': 'shu',
    '竖': 'shu',
    '恕': 'shu',
    '庶': 'shu',
    '耍': 'shua',
    '刷': 'shua',
    '摔': 'shuai',
    '衰': 'shuai',
    '甩': 'shuai',
    '帅': 'shuai',
    '双': 'shuang',
    '霜': 'shuang',
    '爽': 'shuang',
    '水': 'shui',
    '睡': 'shui',
    '税': 'shui',
    '顺': 'shun',
    '瞬': 'shun',
    '说': 'shuo',
    '硕': 'shuo',
    '朔': 'shuo',
    '烁': 'shuo',
    '斯': 'si',
    '撕': 'si',
    '嘶': 'si',
    '思': 'si',
    '私': 'si',
    '司': 'si',
    '丝': 'si',
    '死': 'si',
    '四': 'si',
    '寺': 'si',
    '嗣': 'si',
    '伺': 'si',
    '似': 'si',
    '巳': 'si',
    '松': 'song',
    '耸': 'song',
    '怂': 'song',
    '颂': 'song',
    '送': 'song',
    '宋': 'song',
    '讼': 'song',
    '诵': 'song',
    '搜': 'sou',
    '艘': 'sou',
    '擞': 'sou',
    '嗾': 'sou',
    '苏': 'su',
    '诉': 'su',
    '肃': 'su',
    '素': 'su',
    '速': 'su',
    '粟': 'su',
    '傃': 'su',
    '塑': 'su',
    '溯': 'su',
    '宿': 'su',
    '缩': 'su',
    '酥': 'su',
    '俗': 'su',
    '酸': 'suan',
    '蒜': 'suan',
    '算': 'suan',
    '虽': 'sui',
    '绥': 'sui',
    '隋': 'sui',
    '随': 'sui',
    '髓': 'sui',
    '岁': 'sui',
    '碎': 'sui',
    '穗': 'sui',
    '遂': 'sui',
    '隧': 'sui',
    '祟': 'sui',
    '孙': 'sun',
    '损': 'sun',
    '笋': 'sun',
    '蓑': 'suo',
    '梭': 'suo',
    '嗦': 'suo',
    ' suo': 'suo',
    '所': 'suo',
    '索': 'suo',
    '琐': 'suo',
    '锁': 'suo',
    '他': 'ta',
    '她': 'ta',
    '它': 'ta',
    '塔': 'ta',
    '獭': 'ta',
    '挞': 'ta',
    '拓': 'ta',
    '踏': 'ta',
    '太': 'tai',
    '态': 'tai',
    '肽': 'tai',
    '泰': 'tai',
    '坍': 'tan',
    '摊': 'tan',
    '贪': 'tan',
    '瘫': 'tan',
    '滩': 'tan',
    '坛': 'tan',
    '檀': 'tan',
    '痰': 'tan',
    '潭': 'tan',
    '谭': 'tan',
    '谈': 'tan',
    '坦': 'tan',
    '毯': 'tan',
    '袒': 'tan',
    '碳': 'tan',
    '探': 'tan',
    '叹': 'tan',
    '炭': 'tan',
    '汤': 'tang',
    '塘': 'tang',
    '搪': 'tang',
    '棠': 'tang',
    '糖': 'tang',
    '躺': 'tang',
    '趟': 'tang',
    '烫': 'tang',
    '涛': 'tao',
    '掏': 'tao',
    '滔': 'tao',
    '绦': 'tao',
    '萄': 'tao',
    '桃': 'tao',
    '逃': 'tao',
    '淘': 'tao',
    '陶': 'tao',
    '讨': 'tao',
    '套': 'tao',
    '特': 'te',
    '藤': 'teng',
    '疼': 'teng',
    '腾': 'teng',
    '剔': 'ti',
    '梯': 'ti',
    '踢': 'ti',
    '提': 'ti',
    '题': 'ti',
    '蹄': 'ti',
    '啼': 'ti',
    '体': 'ti',
    '替': 'ti',
    '嚏': 'ti',
    '惕': 'ti',
    '涕': 'ti',
    '剃': 'ti',
    '天': 'tian',
    '添': 'tian',
    '田': 'tian',
    '甜': 'tian',
    '恬': 'tian',
    '舔': 'tian',
    '填': 'tian',
    '腆': 'tian',
    '挑': 'tiao',
    '条': 'tiao',
    '眺': 'tiao',
    '跳': 'tiao',
    '贴': 'tie',
    '铁': 'tie',
    '帖': 'tie',
    '厅': 'ting',
    '听': 'ting',
    '烃': 'ting',
    '亭': 'ting',
    '庭': 'ting',
    '停': 'ting',
    '挺': 'ting',
    '艇': 'ting',
    '通': 'tong',
    '桐': 'tong',
    '酮': 'tong',
    '瞳': 'tong',
    '同': 'tong',
    '铜': 'tong',
    '童': 'tong',
    '统': 'tong',
    '痛': 'tong',
    '桶': 'tong',
    '筒': 'tong',
    '偷': 'tou',
    '头': 'tou',
    '投': 'tou',
    '透': 'tou',
    '凸': 'tu',
    '秃': 'tu',
    '突': 'tu',
    '图': 'tu',
    '徒': 'tu',
    '途': 'tu',
    '涂': 'tu',
    '土': 'tu',
    '吐': 'tu',
    '兔': 'tu',
    '团': 'tuan',
    '湍': 'tuan',
    '推': 'tui',
    '腿': 'tui',
    '退': 'tui',
    '蜕': 'tui',
    '褪': 'tui',
    '吞': 'tun',
    '屯': 'tun',
    '臀': 'tun',
    '拖': 'tuo',
    '托': 'tuo',
    '脱': 'tuo',
    '鸵': 'tuo',
    '陀': 'tuo',
    '驮': 'tuo',
    '驼': 'tuo',
    '椭': 'tuo',
    '妥': 'tuo',
    '唾': 'tuo',
    '挖': 'wa',
    '哇': 'wa',
    '蛙': 'wa',
    '娃': 'wa',
    '瓦': 'wa',
    '袜': 'wa',
    '外': 'wai',
    '弯': 'wan',
    '湾': 'wan',
    '玩': 'wan',
    '顽': 'wan',
    '丸': 'wan',
    '烷': 'wan',
    '完': 'wan',
    '碗': 'wan',
    '挽': 'wan',
    '晚': 'wan',
    '皖': 'wan',
    '宛': 'wan',
    '婉': 'wan',
    '万': 'wan',
    '腕': 'wan',
    '汪': 'wang',
    '王': 'wang',
    '亡': 'wang',
    '网': 'wang',
    '往': 'wang',
    '旺': 'wang',
    '望': 'wang',
    '忘': 'wang',
    '妄': 'wang',
    '威': 'wei',
    '微': 'wei',
    '危': 'wei',
    '韦': 'wei',
    '违': 'wei',
    '桅': 'wei',
    '围': 'wei',
    '唯': 'wei',
    '惟': 'wei',
    '维': 'wei',
    '潍': 'wei',
    '伟': 'wei',
    '伪': 'wei',
    '尾': 'wei',
    '纬': 'wei',
    '蔚': 'wei',
    '味': 'wei',
    '畏': 'wei',
    '胃': 'wei',
    '喂': 'wei',
    '魏': 'wei',
    '位': 'wei',
    '渭': 'wei',
    '未': 'wei',
    '谓': 'wei',
    '尉': 'wei',
    '慰': 'wei',
    '卫': 'wei',
    '温': 'wen',
    '瘟': 'wen',
    '文': 'wen',
    '纹': 'wen',
    '闻': 'wen',
    '蚊': 'wen',
    '吻': 'wen',
    '稳': 'wen',
    '紊': 'wen',
    '问': 'wen',
    '翁': 'weng',
    '嗡': 'weng',
    '瓮': 'weng',
    '挝': 'wo',
    '窝': 'wo',
    '我': 'wo',
    '沃': 'wo',
    '卧': 'wo',
    '握': 'wo',
    '斡': 'wo',
    '无': 'wu',
    '吴': 'wu',
    '芜': 'wu',
    '吾': 'wu',
    '梧': 'wu',
    '五': 'wu',
    '午': 'wu',
    '舞': 'wu',
    '伍': 'wu',
    '坞': 'wu',
    '戊': 'wu',
    '雾': 'wu',
    '晤': 'wu',
    '物': 'wu',
    '勿': 'wu',
    '务': 'wu',
    '误': 'wu',
    '悟': 'wu',
    '西': 'xi',
    '硒': 'xi',
    '矽': 'xi',
    '析': 'xi',
    '嘻': 'xi',
    '吸': 'xi',
    '锡': 'xi',
    '栖': 'xi',
    '稀': 'xi',
    '希': 'xi',
    '息': 'xi',
    '惜': 'xi',
    '悉': 'xi',
    '膝': 'xi',
    '昔': 'xi',
    '熙': 'xi',
    '羲': 'xi',
    '隙': 'xi',
    '系': 'xi',
    '戏': 'xi',
    '细': 'xi',
    '瞎': 'xia',
    '虾': 'xia',
    '匣': 'xia',
    '霞': 'xia',
    '辖': 'xia',
    '暇': 'xia',
    '峡': 'xia',
    '侠': 'xia',
    '狭': 'xia',
    '下': 'xia',
    '夏': 'xia',
    '厦': 'xia',
    '吓': 'xia',
    '先': 'xian',
    '仙': 'xian',
    '鲜': 'xian',
    '咸': 'xian',
    '贤': 'xian',
    '衔': 'xian',
    '舷': 'xian',
    '闲': 'xian',
    '涎': 'xian',
    '弦': 'xian',
    '嫌': 'xian',
    '显': 'xian',
    '险': 'xian',
    '现': 'xian',
    '线': 'xian',
    '限': 'xian',
    '陷': 'xian',
    '馅': 'xian',
    '献': 'xian',
    '县': 'xian',
    '腺': 'xian',
    '乡': 'xiang',
    '相': 'xiang',
    '香': 'xiang',
    '厢': 'xiang',
    '镶': 'xiang',
    '湘': 'xiang',
    '详': 'xiang',
    '翔': 'xiang',
    '箱': 'xiang',
    '想': 'xiang',
    '响': 'xiang',
    '享': 'xiang',
    '巷': 'xiang',
    '项': 'xiang',
    '像': 'xiang',
    '象': 'xiang',
    '向': 'xiang',
    '削': 'xiao',
    '消': 'xiao',
    '宵': 'xiao',
    '萧': 'xiao',
    '硝': 'xiao',
    '霄': 'xiao',
    '销': 'xiao',
    '小': 'xiao',
    '晓': 'xiao',
    '孝': 'xiao',
    '肖': 'xiao',
    '啸': 'xiao',
    '效': 'xiao',
    '笑': 'xiao',
    '协': 'xie',
    '斜': 'xie',
    '胁': 'xie',
    '谐': 'xie',
    '写': 'xie',
    '械': 'xie',
    '卸': 'xie',
    '蟹': 'xie',
    '懈': 'xie',
    '泄': 'xie',
    '泻': 'xie',
    '谢': 'xie',
    '屑': 'xie',
    '薪': 'xin',
    '芯': 'xin',
    '锌': 'xin',
    '欣': 'xin',
    '辛': 'xin',
    '新': 'xin',
    '忻': 'xin',
    '心': 'xin',
    '信': 'xin',
    '兴': 'xing',
    '星': 'xing',
    '腥': 'xing',
    '猩': 'xing',
    '刑': 'xing',
    '型': 'xing',
    '形': 'xing',
    '醒': 'xing',
    '姓': 'xing',
    '杏': 'xing',
    '性': 'xing',
    '凶': 'xiong',
    '兄': 'xiong',
    '胸': 'xiong',
    '匈': 'xiong',
    '汹': 'xiong',
    '雄': 'xiong',
    '熊': 'xiong',
    '休': 'xiu',
    '修': 'xiu',
    '羞': 'xiu',
    '朽': 'xiu',
    '嗅': 'xiu',
    '锈': 'xiu',
    '秀': 'xiu',
    '袖': 'xiu',
    '绣': 'xiu',
    '戌': 'xu',
    '需': 'xu',
    '虚': 'xu',
    '嘘': 'xu',
    '须': 'xu',
    '徐': 'xu',
    '许': 'xu',
    '蓄': 'xu',
    '叙': 'xu',
    '旭': 'xu',
    '绪': 'xu',
    '续': 'xu',
    '序': 'xu',
    '恤': 'xu',
    '絮': 'xu',
    '婿': 'xu',
    '轩': 'xuan',
    '宣': 'xuan',
    '悬': 'xuan',
    '旋': 'xuan',
    '玄': 'xuan',
    '选': 'xuan',
    '癣': 'xuan',
    '眩': 'xuan',
    '绚': 'xuan',
    '靴': 'xue',
    '薛': 'xue',
    '穴': 'xue',
    '学': 'xue',
    '雪': 'xue',
    '血': 'xue',
    '谑': 'xue',
    '勋': 'xun',
    '熏': 'xun',
    '循': 'xun',
    '旬': 'xun',
    '询': 'xun',
    '巡': 'xun',
    '殉': 'xun',
    '汛': 'xun',
    '逊': 'xun',
    '迅': 'xun',
    '押': 'ya',
    '鸦': 'ya',
    '呀': 'ya',
    '鸭': 'ya',
    '牙': 'ya',
    '芽': 'ya',
    '蚜': 'ya',
    '崖': 'ya',
    '涯': 'ya',
    '雅': 'ya',
    '哑': 'ya',
    '亚': 'ya',
    '讶': 'ya',
    '轧': 'ya',
    '烟': 'yan',
    '胭': 'yan',
    '淹': 'yan',
    '咽': 'yan',
    'Yan': 'yan',
    '岩': 'yan',
    '延': 'yan',
    '言': 'yan',
    '炎': 'yan',
    '沿': 'yan',
    '研': 'yan',
    '盐': 'yan',
    '阎': 'yan',
    '蜒': 'yan',
    '彦': 'yan',
    '艳': 'yan',
    '验': 'yan',
    '雁': 'yan',
    '堰': 'yan',
    '燕': 'yan',
    '谚': 'yan',
    '央': 'yang',
    '殃': 'yang',
    '秧': 'yang',
    '扬': 'yang',
    '佯': 'yang',
    '羊': 'yang',
    '洋': 'yang',
    '阳': 'yang',
    '仰': 'yang',
    '氧': 'yang',
    '痒': 'yang',
    '样': 'yang',
    '漾': 'yang',
    '邀': 'yao',
    '腰': 'yao',
    '夭': 'yao',
    '妖': 'yao',
    '摇': 'yao',
    '尧': 'yao',
    '窑': 'yao',
    '谣': 'yao',
    '姚': 'yao',
    '咬': 'yao',
    '舀': 'yao',
    '药': 'yao',
    '要': 'yao',
    '耀': 'yao',
    '椰': 'ye',
    '噎': 'ye',
    '耶': 'ye',
    '爷': 'ye',
    '也': 'ye',
    '冶': 'ye',
    '野': 'ye',
    '叶': 'ye',
    '业': 'ye',
    '页': 'ye',
    '夜': 'ye',
    '液': 'ye',
    '腋': 'ye',
    '一': 'yi',
    '壹': 'yi',
    '医': 'yi',
    '揖': 'yi',
    '铱': 'yi',
    '依': 'yi',
    '伊': 'yi',
    '衣': 'yi',
    '夷': 'yi',
    '遗': 'yi',
    '移': 'yi',
    '仪': 'yi',
    '胰': 'yi',
    '姨': 'yi',
    '葬': 'yi',
    '怡': 'yi',
    '贻': 'yi',
    '颐': 'yi',
    '蚁': 'yi',
    '倚': 'yi',
    '乙': 'yi',
    '矣': 'yi',
    '以': 'yi',
    '艺': 'yi',
    '抑': 'yi',
    '易': 'yi',
    '邑': 'yi',
    '屹': 'yi',
    '亿': 'yi',
    '役': 'yi',
    '臆': 'yi',
    '逸': 'yi',
    '肄': 'yi',
    '裔': 'yi',
    '意': 'yi',
    '缢': 'yi',
    '肆': 'yi',
    '议': 'yi',
    '亦': 'yi',
    '异': 'yi',
    '翼': 'yi',
    '译': 'yi',
    '益': 'yi',
    '溢': 'yi',
    '毅': 'yi',
    '翌': 'yi',
    '因': 'yin',
    '茵': 'yin',
    '荫': 'yin',
    '音': 'yin',
    '阴': 'yin',
    '姻': 'yin',
    '吟': 'yin',
    '银': 'yin',
    '寅': 'yin',
    '饮': 'yin',
    '尹': 'yin',
    '引': 'yin',
    '隐': 'yin',
    '印': 'yin',
    '英': 'ying',
    '樱': 'ying',
    '婴': 'ying',
    '应': 'ying',
    '缨': 'ying',
    '鹰': 'ying',
    '迎': 'ying',
    '莹': 'ying',
    '萤': 'ying',
    '营': 'ying',
    '荧': 'ying',
    '蝇': 'ying',
    '赢': 'ying',
    '盈': 'ying',
    '颖': 'ying',
    '影': 'ying',
    '映': 'ying',
    '硬': 'ying',
    '哟': 'yo',
    '拥': 'yong',
    '佣': 'yong',
    '臃': 'yong',
    '痈': 'yong',
    '雍': 'yong',
    '蛹': 'yong',
    '泳': 'yong',
    '咏': 'yong',
    '涌': 'yong',
    '永': 'yong',
    '恿': 'yong',
    '勇': 'yong',
    '用': 'yong',
    '幽': 'you',
    '优': 'you',
    '悠': 'you',
    '忧': 'you',
    '尤': 'you',
    '由': 'you',
    '邮': 'you',
    '铀': 'you',
    '犹': 'you',
    '油': 'you',
    '游': 'you',
    '酉': 'you',
    '有': 'you',
    '友': 'you',
    '右': 'you',
    '佑': 'you',
    '釉': 'you',
    '诱': 'you',
    '又': 'you',
    '幼': 'you',
    '迂': 'yu',
    '淤': 'yu',
    '于': 'yu',
    '盂': 'yu',
    '榆': 'yu',
    '虞': 'yu',
    '愚': 'yu',
    '舆': 'yu',
    '余': 'yu',
    '俞': 'yu',
    '逾': 'yu',
    '渝': 'yu',
    '愉': 'yu',
    '瑜': 'yu',
    '觎': 'yu',
    '与': 'yu',
    '屿': 'yu',
    '禹': 'yu',
    '宇': 'yu',
    '语': 'yu',
    '玉': 'yu',
    '雨': 'yu',
    '域': 'yu',
    '芋': 'yu',
    '郁': 'yu',
    '育': 'yu',
    '浴': 'yu',
    '预': 'yu',
    '裕': 'yu',
    '遇': 'yu',
    '寓': 'yu',
    '誉': 'yu',
    '御': 'yu',
    '愈': 'yu',
    '豫': 'yu',
    '欲': 'yu',
    '狱': 'yu',
    '谕': 'yu',
    '元': 'yuan',
    '原': 'yuan',
    '袁': 'yuan',
    '园': 'yuan',
    '援': 'yuan',
    '猿': 'yuan',
    '圆': 'yuan',
    '源': 'yuan',
    '缘': 'yuan',
    '远': 'yuan',
    '怨': 'yuan',
    '院': 'yuan',
    '愿': 'yuan',
    '约': 'yue',
    '月': 'yue',
    '悦': 'yue',
    '阅': 'yue',
    '跃': 'yue',
    '越': 'yue',
    '岳': 'yue',
    '粤': 'yue',
    '云': 'yun',
    '匀': 'yun',
    '陨': 'yun',
    '允': 'yun',
    '运': 'yun',
    '蕴': 'yun',
    '孕': 'yun',
    '韵': 'yun',
    '员': 'yun',
    '杂': 'za',
    '砸': 'za',
    '灾': 'zai',
    '哉': 'zai',
    '栽': 'zai',
    '宰': 'zai',
    '载': 'zai',
    '再': 'zai',
    '在': 'zai',
    '咱': 'zan',
    '攒': 'zan',
    '暂': 'zan',
    '赞': 'zan',
    '赃': 'zang',
    '脏': 'zang',
    '遭': 'zao',
    '糟': 'zao',
    '凿': 'zao',
    '藻': 'zao',
    '早': 'zao',
    '枣': 'zao',
    '蚤': 'zao',
    '澡': 'zao',
    '皂': 'zao',
    '灶': 'zao',
    '燥': 'zao',
    '躁': 'zao',
    '则': 'ze',
    '责': 'ze',
    '择': 'ze',
    '泽': 'ze',
    '啧': 'ze',
    '帧': 'zheng',
    '贼': 'zei',
    '怎': 'zen',
    '增': 'zeng',
    '憎': 'zeng',
    '赠': 'zeng',
    '扎': 'zha',
    '喳': 'zha',
    '渣': 'zha',
    '札': 'zha',
    '闸': 'zha',
    '眨': 'zha',
    '榨': 'zha',
    '咋': 'zha',
    '乍': 'zha',
    '炸': 'zha',
    '诈': 'zha',
    '摘': 'zhai',
    '斋': 'zhai',
    '宅': 'zhai',
    '窄': 'zhai',
    '债': 'zhai',
    '寨': 'zhai',
    '占': 'zhan',
    '战': 'zhan',
    '站': 'zhan',
    '湛': 'zhan',
    '绽': 'zhan',
    '栈': 'zhan',
    '张': 'zhang',
    '涨': 'zhang',
    '掌': 'zhang',
    '丈': 'zhang',
    '仗': 'zhang',
    '杖': 'zhang',
    '帐': 'zhang',
    '账': 'zhang',
    '胀': 'zhang',
    '障': 'zhang',
    '招': 'zhao',
    '找': 'zhao',
    '沼': 'zhao',
    '赵': 'zhao',
    '照': 'zhao',
    '罩': 'zhao',
    '兆': 'zhao',
    '肇': 'zhao',
    '召': 'zhao',
    '昭': 'zhao',
    '着': 'zhao',
    '诏': 'zhao',
    '折': 'zhe',
    '辙': 'zhe',
    '遮': 'zhe',
    '哲': 'zhe',
    '蛰': 'zhe',
    '者': 'zhe',
    '浙': 'zhe',
    '蔗': 'zhe',
    '这': 'zhe',
    '柘': 'zhe',
    '珍': 'zhen',
    '真': 'zhen',
    '诊': 'zhen',
    '枕': 'zhen',
    '疹': 'zhen',
    '镇': 'zhen',
    '震': 'zhen',
    '振': 'zhen',
    '阵': 'zhen',
    '挣': 'zheng',
    '睁': 'zheng',
    '征': 'zheng',
    '蒸': 'zheng',
    '证': 'zheng',
    '郑': 'zheng',
    '怔': 'zheng',
    '整': 'zheng',
    '争': 'zheng',
    '正': 'zheng',
    '政': 'zheng',
    '症': 'zheng',
    '之': 'zhi',
    '芝': 'zhi',
    '支': 'zhi',
    '枝': 'zhi',
    '吱': 'zhi',
    '肢': 'zhi',
    '脂': 'zhi',
    '汁': 'zhi',
    '织': 'zhi',
    '知': 'zhi',
    '蜘': 'zhi',
    '只': 'zhi',
    '指': 'zhi',
    '职': 'zhi',
    '止': 'zhi',
    '址': 'zhi',
    '趾': 'zhi',
    '旨': 'zhi',
    '至': 'zhi',
    '志': 'zhi',
    '制': 'zhi',
    '治': 'zhi',
    '峙': 'zhi',
    '质': 'zhi',
    '致': 'zhi',
    '智': 'zhi',
    '滞': 'zhi',
    '稚': 'zhi',
    '置': 'zhi',
    '酯': 'zhi',
    '中': 'zhong',
    '盅': 'zhong',
    '忠': 'zhong',
    '钟': 'zhong',
    '衷': 'zhong',
    '终': 'zhong',
    '肿': 'zhong',
    '重': 'zhong',
    '种': 'zhong',
    '仲': 'zhong',
    '众': 'zhong',
    '舟': 'zhou',
    '周': 'zhou',
    '州': 'zhou',
    '粥': 'zhou',
    '肘': 'zhou',
    '帚': 'zhou',
    '皱': 'zhou',
    '骤': 'zhou',
    '轴': 'zhou',
    '宙': 'zhou',
    '昼': 'zhou',
    '珠': 'zhu',
    '株': 'zhu',
    '蛛': 'zhu',
    '朱': 'zhu',
    '猪': 'zhu',
    '诸': 'zhu',
    '诛': 'zhu',
    '逐': 'zhu',
    '竹': 'zhu',
    '烛': 'zhu',
    '煮': 'zhu',
    '拄': 'zhu',
    '嘱': 'zhu',
    '主': 'zhu',
    '柱': 'zhu',
    '住': 'zhu',
    '注': 'zhu',
    '祝': 'zhu',
    '驻': 'zhu',
    '爪': 'zhua',
    '筑': 'zhu',
    '专': 'zhuan',
    '砖': 'zhuan',
    '转': 'zhuan',
    '撰': 'zhuan',
    '赚': 'zhuan',
    '篆': 'zhuan',
    '桩': 'zhuang',
    '庄': 'zhuang',
    '妆': 'zhuang',
    '装': 'zhuang',
    '撞': 'zhuang',
    '壮': 'zhuang',
    '状': 'zhuang',
    '准': 'zhun',
    '卓': 'zhuo',
    '桌': 'zhuo',
    '拙': 'zhuo',
    '捉': 'zhuo',
    '灼': 'zhuo',
    '浊': 'zhuo',
    '琢': 'zhuo',
    '茁': 'zhuo',
    '啄': 'zhuo',
    '酌': 'zhuo',
    '子': 'zi',
    '仔': 'zi',
    '籽': 'zi',
    '紫': 'zi',
    '自': 'zi',
    '滓': 'zi',
    '字': 'zi',
    '渍': 'zi',
    '姿': 'zi',
    '滋': 'zi',
    '兹': 'zi',
    '咨': 'zi',
    '资': 'zi',
    'ZL': 'zi',
    '宗': 'zong',
    '棕': 'zong',
    '踪': 'zong',
    '总': 'zong',
    '纵': 'zong',
    '粽': 'zong',
    '邹': 'zou',
    '走': 'zou',
    '奏': 'zou',
    '揍': 'zou',
    '租': 'zu',
    '足': 'zu',
    '卒': 'zu',
    '族': 'zu',
    '诅': 'zu',
    '阻': 'zu',
    '组': 'zu',
    '祖': 'zu',
    '钻': 'zuan',
    '攥': 'zuan',
    '嘴': 'zui',
    '最': 'zui',
    '罪': 'zui',
    '醉': 'zui',
    '尊': 'zun',
    '遵': 'zun',
    '昨': 'zuo',
    '左': 'zuo',
    '佐': 'zuo',
    '做': 'zuo',
    '坐': 'zuo',
    '座': 'zuo',
    '柞': 'zuo'
  };
  
  // 简单实现：逐字符转换
  let result = '';
  for (const char of chinese) {
    if (pinyinMap[char]) {
      result += pinyinMap[char];
    } else {
      // 无法转换的保留原字符
      result += char;
    }
  }
  
  // 清理并转为小写
  return result
    .toLowerCase()
    .replace(/[^a-z0-9]/g, '')
    .substring(0, 50); // 限制长度
}

/**
 * 统一登录接口（支持系统用户和租户用户）
 * POST /api/v1/auth/login
 */
export const systemLogin = async (req: Request, res: Response) => {
  try {
    const { username, password } = req.body;

    // 验证参数
    if (!username || !password) {
      return res.status(400).json({
        success: false,
        message: '用户名和密码不能为空',
      });
    }

    let user: any = null;
    let userType: 'system' | 'tenant' = 'system';

    // 先查询系统用户表（支持用户名、姓名、邮箱三种方式登录）
    console.log('Searching for user:', username);
    
    user = await prisma.systemUser.findFirst({
      where: {
        OR: [
          { email: username },
          { name: username },
        ],
      },
      include: { tenant: true },
    });

    console.log('Found system user:', user ? user.email : 'null');

    // 如果系统用户表找不到，查询租户用户表
    if (!user) {
      user = await prisma.user.findFirst({
        where: {
          OR: [
            { email: username },
            { name: username },
          ],
        },
        include: { tenant: true },
      });
      userType = 'tenant';
    }

    if (!user || user.status !== 'active') {
      return res.status(401).json({
        success: false,
        message: '用户名或密码错误',
      });
    }

    // 验证密码
    const isPasswordValid = await bcrypt.compare(password, user.password);
    if (!isPasswordValid) {
      return res.status(401).json({
        success: false,
        message: '用户名或密码错误',
      });
    }

    // 检查租户有效期（仅租户用户）
    let trialWarning = null;
    let expiredMessage = null;

    if (userType === 'tenant' && user.tenant) {
      const now = new Date();

      // 检查试用期到期（仅在租户状态为 trial 时）
      if (user.tenant.status === 'trial' && user.tenant.trialEndsAt) {
        const trialEndsAt = new Date(user.tenant.trialEndsAt);
        const remainingDays = Math.ceil((trialEndsAt.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));

        if (remainingDays <= 0) {
          expiredMessage = `租户试用期已到期（${trialEndsAt.toLocaleDateString('zh-CN')}），请联系管理员续费或升级订阅。`;
        } else if (remainingDays <= 7) {
          trialWarning = {
            type: 'warning',
            title: '租户试用期即将到期',
            message: `您的租户试用期还剩 ${remainingDays} 天，将于 ${trialEndsAt.toLocaleDateString('zh-CN')} 到期。`,
            daysRemaining: remainingDays,
            expiresAt: trialEndsAt.toISOString()
          };
        }
      }

      // 检查订阅周期到期（付费用户）
      if (!expiredMessage && user.tenant.currentPeriodEndsAt) {
        const periodEndsAt = new Date(user.tenant.currentPeriodEndsAt);
        const remainingDays = Math.ceil((periodEndsAt.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));

        if (remainingDays <= 0) {
          expiredMessage = `订阅服务已到期（${periodEndsAt.toLocaleDateString('zh-CN')}），请续费继续使用。`;
        } else if (remainingDays <= 7 && !trialWarning) {
          trialWarning = {
            type: 'warning',
            title: '订阅服务即将到期',
            message: `您的订阅服务还剩 ${remainingDays} 天，将于 ${periodEndsAt.toLocaleDateString('zh-CN')} 到期。`,
            daysRemaining: remainingDays,
            expiresAt: periodEndsAt.toISOString()
          };
        }
      }

      // 如果已过期，禁止登录
      if (expiredMessage) {
        return res.status(403).json({
          success: false,
          message: expiredMessage,
        });
      }
    }

    // 更新最后登录时间（仅租户用户）
    if (userType === 'tenant') {
      await prisma.user.update({
        where: { id: user.id },
        data: { lastLoginAt: new Date() },
      });
    }

    // 生成token（根据用户类型包含不同的 payload）
    const tokenPayload: any = {
      id: user.id,
      email: user.email,
      role: user.role,
    };

    if (userType === 'tenant' && user.tenantId) {
      tokenPayload.tenantId = user.tenantId;
    }

    const token = generateToken(tokenPayload);

    // 记录审计日志
    await auditLog({
      ...(userType === 'tenant' && { tenantId: user.tenantId }),
      userId: user.id,
      action: 'login',
      module: 'auth',
      detail: JSON.stringify({ username, email: user.email, name: user.name, role: user.role, userType }),
      ip: req.ip,
      userAgent: req.get('user-agent'),
    });

    // 构建响应数据（根据用户类型返回不同的数据结构）
    const responseData: any = {
      token,
      user: {
        id: user.id,
        email: user.email,
        name: user.name,
        role: user.role,
      },
    };

    // 如果是租户用户，包含租户信息
    if (userType === 'tenant' && user.tenant) {
      responseData.user.tenant = {
        id: user.tenant.id,
        name: user.tenant.name,
        slug: user.tenant.slug,
        plan: user.tenant.plan,
        trialEndsAt: user.tenant.trialEndsAt,
        trialWarning: trialWarning,
      };
    }
    
    // 系统用户也包含租户信息（系统租户）
    if (userType === 'system' && user.tenant) {
      responseData.user.tenant = {
        id: user.tenant.id,
        name: user.tenant.name,
        slug: user.tenant.slug,
        isSystem: user.tenant.isSystem || false,
        initializationStatus: user.tenant.initializationStatus || 'pending',
      };
    }

    return res.json({
      success: true,
      data: responseData,
      message: '登录成功',
    });
  } catch (error) {
    console.error('登录错误:', error);
    return res.status(500).json({
      success: false,
      message: '登录失败',
    });
  }
};

/**
 * 租户用户登录
 * POST /api/v1/auth/tenant/login
 */
export const tenantLogin = async (req: Request, res: Response) => {
  try {
    const { username, password, tenantSlug } = req.body;

    // 验证参数
    if (!username || !password) {
      return res.status(400).json({
        success: false,
        message: '用户名和密码不能为空',
      });
    }

    // 查询租户（如果提供了slug）
    let tenantId: string | undefined;
    if (tenantSlug) {
      const tenant = await prisma.tenant.findUnique({
        where: { slug: tenantSlug },
      });

      if (!tenant) {
        return res.status(404).json({
          success: false,
          message: '租户不存在',
        });
      }

      if (tenant.status && !['active', 'trial'].includes(tenant.status)) {
        return res.status(403).json({
          success: false,
          message: `租户状态异常: ${tenant.status}`,
        });
      }

      tenantId = tenant.id;
    }

    // 查询用户（支持用户名、姓名、邮箱三种方式登录）
    const user = await prisma.user.findFirst({
      where: {
        OR: [
          { email: username },
          { name: username },
        ],
        ...(tenantId && { tenantId }),
      },
      include: { tenant: true },
    });

    if (!user || user.status !== 'active') {
      return res.status(401).json({
        success: false,
        message: '用户名或密码错误',
      });
    }

    // 验证密码
    const isPasswordValid = await bcrypt.compare(password, user.password);
    if (!isPasswordValid) {
      return res.status(401).json({
        success: false,
        message: '用户名或密码错误',
      });
    }

    // 检查租户状态
    if (user.tenant && !['active', 'trial'].includes(user.tenant.status)) {
      return res.status(403).json({
        success: false,
        message: `租户状态异常: ${user.tenant.status}`,
      });
    }

    // 检查租户有效期（试用期和订阅周期）
    let trialWarning = null;
    let expiredMessage = null;
    const now = new Date();

    if (user.tenant) {
      // 检查试用期到期（仅在租户状态为 trial 时）
      if (user.tenant.status === 'trial' && user.tenant.trialEndsAt) {
        const trialEndsAt = new Date(user.tenant.trialEndsAt);
        const remainingDays = Math.ceil((trialEndsAt.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));

        if (remainingDays <= 0) {
          expiredMessage = `租户试用期已到期（${trialEndsAt.toLocaleDateString('zh-CN')}），请联系管理员续费或升级订阅。`;
        } else if (remainingDays <= 7) {
          trialWarning = {
            type: 'warning',
            title: '租户试用期即将到期',
            message: `您的租户试用期还剩 ${remainingDays} 天，将于 ${trialEndsAt.toLocaleDateString('zh-CN')} 到期。`,
            daysRemaining: remainingDays,
            expiresAt: trialEndsAt.toISOString()
          };
        }
      }

      // 检查订阅周期到期（付费用户）
      if (!expiredMessage && user.tenant.currentPeriodEndsAt) {
        const periodEndsAt = new Date(user.tenant.currentPeriodEndsAt);
        const remainingDays = Math.ceil((periodEndsAt.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));

        if (remainingDays <= 0) {
          expiredMessage = `订阅服务已到期（${periodEndsAt.toLocaleDateString('zh-CN')}），请续费继续使用。`;
        } else if (remainingDays <= 7 && !trialWarning) {
          trialWarning = {
            type: 'warning',
            title: '订阅服务即将到期',
            message: `您的订阅服务还剩 ${remainingDays} 天，将于 ${periodEndsAt.toLocaleDateString('zh-CN')} 到期。`,
            daysRemaining: remainingDays,
            expiresAt: periodEndsAt.toISOString()
          };
        }
      }

      // 如果已过期，禁止登录
      if (expiredMessage) {
        return res.status(403).json({
          success: false,
          message: expiredMessage,
        });
      }
    }

    // 更新最后登录时间
    await prisma.user.update({
      where: { id: user.id },
      data: { lastLoginAt: new Date() },
    });

    // 生成token
    const token = generateToken({
      id: user.id,
      email: user.email,
      role: user.role,
      tenantId: user.tenantId,
    });

    // 记录审计日志
    await auditLog({
      tenantId: user.tenantId,
      userId: user.id,
      action: 'login',
      module: 'auth',
      detail: JSON.stringify({ username, email: user.email, name: user.name, role: user.role, tenantId: user.tenantId }),
      ip: req.ip,
      userAgent: req.get('user-agent'),
    });

    return res.json({
      success: true,
      data: {
        token,
        user: {
          id: user.id,
          email: user.email,
          name: user.name,
          role: user.role,
          tenant: user.tenant ? {
            id: user.tenant.id,
            name: user.tenant.name,
            slug: user.tenant.slug,
            plan: user.tenant.plan,
            trialEndsAt: user.tenant.trialEndsAt,
            trialWarning: trialWarning,
            initializationStatus: user.tenant.initializationStatus || 'pending',
          } : null,
        },
      },
      message: '登录成功',
    });
  } catch (error) {
    console.error('租户登录错误:', error);
    return res.status(500).json({
      success: false,
      message: '登录失败',
    });
  }
};

/**
 * 用户注册（创建租户 + 管理员账号）
 * POST /api/v1/auth/register
 */
export const register = async (req: Request, res: Response) => {
  try {
    // 兼容前后端参数：支持 email 和 username
    const { username, email, name, password, tenantName, tenantSlug } = req.body;
    const emailOrUsername = email || username; // 优先使用 email，否则使用 username

    if (!emailOrUsername || !name || !password || !tenantName || !tenantSlug) {
      return res.status(400).json({
        success: false,
        message: '参数不完整',
      });
    }

    // 检查用户名是否已存在（系统用户）
    const existingSystemUser = await prisma.systemUser.findUnique({
      where: { email: emailOrUsername },
    });

    if (existingSystemUser) {
      return res.status(400).json({
        success: false,
        message: '用户名已被注册',
      });
    }

    // 检查用户是否已经创建过租户（限制只能试用一次）
    const existingUserWithTenant = await prisma.user.findFirst({
      where: { email: emailOrUsername },
    });

    if (existingUserWithTenant) {
      return res.status(400).json({
        success: false,
        message: '该用户名已注册过租户，如需继续使用请联系管理员',
      });
    }

    // 检查租户名称是否已存在
    const existingTenantByName = await prisma.tenant.findFirst({
      where: { name: tenantName },
    });

    if (existingTenantByName) {
      return res.status(400).json({
        success: false,
        message: '机构名称已存在',
      });
    }

    // 检查租户标识是否已存在（支持中文slug）
    // 如果输入的是纯中文，自动转换为拼音slug
    let finalSlug = tenantSlug;
    
    // 如果slug是纯中文，转换为拼音
    if (/^[\u4e00-\u9fa5]+$/.test(tenantSlug)) {
      // 使用拼音转换
      finalSlug = convertToPinyin(tenantSlug);
    }
    
    const existingTenantBySlug = await prisma.tenant.findUnique({
      where: { slug: finalSlug },
    });

    if (existingTenantBySlug) {
      return res.status(400).json({
        success: false,
        message: '机构标识已存在',
      });
    }

    // 加密密码
    const hashedPassword = await bcrypt.hash(password, 10);

    // 创建租户和管理员用户（事务）
    const result = await prisma.$transaction(async (tx) => {
      // 创建租户
      const tenant = await tx.tenant.create({
        data: {
          name: tenantName,
          slug: finalSlug, // 使用处理后的slug
          plan: config.tenant.defaultPlan,
          status: 'trial',
          trialEndsAt: new Date(Date.now() + config.tenant.defaultTrialDays * 24 * 60 * 60 * 1000),
        },
      });

      // 创建管理员用户（租户内用户）
      const user = await tx.user.create({
        data: {
          tenantId: tenant.id,
          email: emailOrUsername,
          username: emailOrUsername, // 使用邮箱作为用户名
          password: hashedPassword,
          name,
          code: generateUserCode(tenant.id), // 生成人员编码
          role: 'admin',
          status: 'active',
          isSystemUser: true, // 管理员是系统用户，可以登录
        },
      });

      return { tenant, user };
    });

    // 生成token
    const token = generateToken({
      id: result.user.id,
      email: result.user.email,
      role: result.user.role,
      tenantId: result.tenant.id,
    });

    // 记录审计日志
    await auditLog({
      tenantId: result.tenant.id,
      userId: result.user.id, // 确保这是 User 表的 ID
      action: 'create',
      module: 'tenant',
      resource: result.tenant.id,
      detail: JSON.stringify({ tenantName, tenantSlug: finalSlug, email: emailOrUsername, name }),
      ip: req.ip,
      userAgent: req.get('user-agent'),
    });

    return res.status(201).json({
      success: true,
      data: {
        token,
        tenant: {
          id: result.tenant.id,
          name: result.tenant.name,
          slug: result.tenant.slug,
          plan: result.tenant.plan,
          status: result.tenant.status,
          trialEndsAt: result.tenant.trialEndsAt,
        },
        user: {
          id: result.user.id,
          email: result.user.email,
          name: result.user.name,
          role: result.user.role,
        },
      },
      message: '注册成功',
    });
  } catch (error) {
    console.error('注册错误:', error);
    return res.status(500).json({
      success: false,
      message: '注册失败',
    });
  }
};

/**
 * 获取当前用户信息
 * GET /api/v1/auth/me
 */
export const getMe = async (req: Request, res: Response) => {
  try {
    if (!req.user) {
      return res.status(401).json({
        success: false,
        message: '未认证',
      });
    }

    let user: any;

    if (req.user.role === 'super_admin' || req.user.role === 'tenant_admin') {
      // 系统用户
      user = await prisma.systemUser.findUnique({
        where: { id: req.user.id },
        include: { tenant: true },
      });
    } else {
      // 租户用户
      user = await prisma.user.findUnique({
        where: { id: req.user.id },
        include: { tenant: true },
      });
    }

    if (!user) {
      return res.status(404).json({
        success: false,
        message: '用户不存在',
      });
    }

    return res.json({
      success: true,
      data: {
        user: {
          id: user.id,
          email: user.email,
          name: user.name,
          role: user.role,
          tenant: user.tenant ? {
            id: user.tenant.id,
            name: user.tenant.name,
            slug: user.tenant.slug,
            plan: user.tenant.plan,
            status: user.tenant.status,
            initializationStatus: user.tenant.initializationStatus,
          } : null,
        },
      },
    });
  } catch (error) {
    console.error('获取用户信息错误:', error);
    return res.status(500).json({
      success: false,
      message: '获取用户信息失败',
    });
  }
};

/**
 * 修改密码
 * POST /api/v1/auth/change-password
 */
export const changePassword = async (req: Request, res: Response) => {
  try {
    if (!req.user) {
      return res.status(401).json({
        success: false,
        message: '未认证',
      });
    }

    const { oldPassword, newPassword } = req.body;

    if (!oldPassword || !newPassword) {
      return res.status(400).json({
        success: false,
        message: '旧密码和新密码不能为空',
      });
    }

    if (newPassword.length < 6) {
      return res.status(400).json({
        success: false,
        message: '新密码长度至少6位',
      });
    }

    let user: any;

    // 查询用户
    if (req.user.role === 'super_admin' || req.user.role === 'tenant_admin') {
      user = await prisma.systemUser.findUnique({
        where: { id: req.user.id },
      });
    } else {
      user = await prisma.user.findUnique({
        where: { id: req.user.id },
      });
    }

    if (!user) {
      return res.status(404).json({
        success: false,
        message: '用户不存在',
      });
    }

    // 验证旧密码
    const isPasswordValid = await bcrypt.compare(oldPassword, user.password);
    if (!isPasswordValid) {
      return res.status(401).json({
        success: false,
        message: '旧密码错误',
      });
    }

    // 加密新密码
    const hashedNewPassword = await bcrypt.hash(newPassword, 10);

    // 更新密码
    if (req.user.role === 'super_admin' || req.user.role === 'tenant_admin') {
      await prisma.systemUser.update({
        where: { id: req.user.id },
        data: { password: hashedNewPassword },
      });
    } else {
      await prisma.user.update({
        where: { id: req.user.id },
        data: { password: hashedNewPassword },
      });
    }

    // 记录审计日志
    await auditLog({
      tenantId: req.user.tenantId,
      userId: req.user.id,
      action: 'update',
      module: 'auth',
      detail: JSON.stringify({ action: 'change_password' }),
      ip: req.ip,
      userAgent: req.get('user-agent'),
    });

    return res.json({
      success: true,
      message: '密码修改成功',
    });
  } catch (error) {
    console.error('修改密码错误:', error);
    return res.status(500).json({
      success: false,
      message: '修改密码失败',
    });
  }
};

/**
 * 刷新Token
 * POST /api/v1/auth/refresh
 */
export const refreshToken = async (req: Request, res: Response) => {
  try {
    if (!req.user) {
      return res.status(401).json({
        success: false,
        message: '未认证',
      });
    }

    // 生成新token
    const newToken = generateToken({
      id: req.user.id,
      email: req.user.email,
      role: req.user.role,
      tenantId: req.user.tenantId,
    });

    return res.json({
      success: true,
      data: {
        token: newToken,
      },
      message: 'Token刷新成功',
    });
  } catch (error) {
    console.error('刷新Token错误:', error);
    return res.status(500).json({
      success: false,
      message: '刷新Token失败',
    });
  }
};

/**
 * 登出
 * POST /api/v1/auth/logout
 */
export const logout = async (req: Request, res: Response) => {
  try {
    if (!req.user) {
      return res.status(401).json({
        success: false,
        message: '未认证',
      });
    }

    // 记录审计日志（SystemUser 不设置 userId，避免外键约束错误）
    await auditLog({
      ...(req.user.tenantId && { tenantId: req.user.tenantId }),
      // 只有普通租户用户才设置 userId，超级管理员不设置
      ...(req.user.tenantId && { userId: req.user.id }),
      action: 'logout',
      module: 'auth',
      detail: JSON.stringify({ userId: req.user.id, email: req.user.email, name: req.user.name }),
      ip: req.ip,
      userAgent: req.get('user-agent'),
    });

    // 客户端需要删除本地存储的token
    return res.json({
      success: true,
      message: '登出成功',
    });
  } catch (error) {
    console.error('登出错误:', error);
    return res.status(500).json({
      success: false,
      message: '登出失败',
    });
  }
};

/**
 * 根据用户名搜索可用的租户列表
 * GET /api/v1/auth/search-tenants
 */
export const searchTenantsByUsername = async (req: Request, res: Response) => {
  try {
    const { username } = req.query;

    if (!username || typeof username !== 'string') {
      return res.json({
        success: true,
        data: { tenants: [], count: 0 },
      });
    }

    const tenants: any[] = [];

    // 查询系统用户
    try {
      const systemUsers = await prisma.systemUser.findMany({
        where: {
          OR: [
            { email: username },
            { name: username },
          ],
        },
        include: { tenant: true },
      });

      for (const user of systemUsers) {
        if (user.tenant) {
          tenants.push({
            id: user.tenant.id,
            name: user.tenant.name,
            slug: user.tenant.slug,
            isSystem: user.tenant.isSystem || false,
          });
        }
      }
    } catch (e) {
      console.error('查询系统用户失败:', e);
    }

    // 查询租户用户
    try {
      const tenantUsers = await prisma.user.findMany({
        where: {
          OR: [
            { email: username },
            { name: username },
          ],
        },
        include: { tenant: true },
      });

      for (const user of tenantUsers) {
        if (user.tenant && !tenants.find(t => t.id === user.tenant!.id)) {
          tenants.push({
            id: user.tenant.id,
            name: user.tenant.name,
            slug: user.tenant.slug,
          });
        }
      }
    } catch (e) {
      console.error('查询租户用户失败:', e);
    }

    // 去重
    const uniqueTenants = tenants.filter((t, index, arr) => 
      arr.findIndex(x => x.id === t.id) === index
    );

    return res.json({
      success: true,
      data: { tenants: uniqueTenants, count: uniqueTenants.length },
    });
  } catch (error) {
    console.error('搜索租户错误:', error);
    return res.json({
      success: true,
      data: { tenants: [], count: 0 },
    });
  }
};

// 验证用户名密码，返回该用户所属的租户列表
export default {
  systemLogin,
  tenantLogin,
  register,
  getMe,
  changePassword,
  refreshToken,
  logout,
  searchTenantsByUsername,
};
